---
title: "WormBase Gene Identifiers"
output: html_document
---

```{r setup}
library(readr)
source("wormbaseFtp.R")
```

```{r geneId}
wormbaseFile("geneIDs")
df <- read_csv(geneIds, col_names = FALSE, na = "")

# Discard uneeded columns
df <- df[, c(2, 4, 3, 5)]

colnames(df) <- c("geneId", "orf", "publicName", "status")
rownames(df) <- df$geneId
geneId <- df
```

```{r geneOtherIds}
wormbaseFile("geneOtherIDs")
file <- read_file(geneOtherIds)

# Take out dead or live status, we have this already from geneIds
file <- gsub("\t(Dead|Live)", "", file, perl = TRUE)

# Take the tabs out for gene list
file <- gsub("\t", ", ", file)

# Add tab back in to separate geneId for row names
file <- gsub("WBGene([0-9]+), ", "WBGene\\1\t", file, perl = TRUE)

# Warnings here mean there are no other IDs for that row
# (e.g. expected: 2 columns, actual: 1 columns)
df <- suppressWarnings(read_tsv(file, col_names = FALSE))

rownames(df) <- df[, 1]
colnames(df) <- c("geneId", "geneOtherIds")
df <- df[rownames(geneId), ]
df$geneId <- NULL
geneOtherIds <- df
```

``` {r save}
wormbaseGeneId <- cbind(geneId, geneOtherIds)
devtools::use_data(wormbaseGeneId, overwrite = TRUE)
warnings()
```
