---
title: "WormBase annotations"
date: "`r BiocStyle::doc_date()`"
author: "Michael J. Steinbaugh"
---

```{r setup, include=FALSE}
source("setup.R")
```

# Gene

```{r gene}
geneIDs <- wormbaseAnnotationFile("geneIDs") %>%
    read_csv(col_names = c("X", "gene", "name", "sequence", "status"),
             na = "") %>%
    select(-X)
geneOtherIDs <- wormbaseAnnotationFile("geneOtherIDs") %>%
    read_file %>%
    # Strip out live/dead status, already have in gene
    str_replace_all("\t(Dead|Live)", "") %>%
    # Take the tabs out for gene list
    str_replace_all("\t", ", ") %>%
    # Add tab back in to separate \code{gene} for row names
    str_replace_all("WBGene(\\d+), ", "WBGene\\1\t") %>%
    # Warnings here mean there are no other IDs for that row
    # (e.g. expected: 2 columns, actual: 1 columns)
    read_tsv(col_names = c("gene", "otherIdentifier"))
gene <- left_join(geneIDs, geneOtherIDs, by = "gene")
rm(geneIDs, geneOtherIDs)
```



# Description

```{r description}
file <- wormbaseAnnotationFile("functional_descriptions")
names <- read_lines(file, n_max = 1, skip = 3) %>%
    str_split(" ") %>%
    .[[1]] %>%
    str_replace_all("(\\w+)_description$", "description_\\1") %>%
    camel %>%
    str_replace("descriptionGeneClass", "class") %>%
    str_replace("geneId", "gene") %>%
    str_replace("molecularName", "sequence") %>%
    str_replace("publicName", "name")
print(names)
description <- read_delim(file, delim = "\t",
               col_names = names,
               skip = 4,
               na = c("", "none available", "not known")) %>%
    select(-c(name, sequence)) %>%
    filter(grepl("^WBGene\\d+$", gene))
rm(file, names)
```



# Ortholog

```{r otholog}
raw <- wormbaseAnnotationFile("orthologs") %>%
    read_file %>%
    gsub("\t", " | ", .) %>%
    gsub("\n", " // ", .) %>%
    gsub("= // ", "\n", .) %>%
    gsub(" //  // ", "\t", .) %>%
    read_tsv(comment = "#", col_names = c("gene", "ortholog")) %>%
    mutate(gene = gsub("^(WBGene[0-9]{8}).*", "\\1", gene))
list <- split(raw, seq(nrow(raw)))
hsapiens <-
    mclapply(seq_along(list), function(a) {
        str_split(list[[a]][2], " // ")[[1]] %>%
            str_subset("Homo sapiens") %>%
            str_extract("ENSG[0-9]{11} \\| [^ ]+") %>%
            gsub(" \\| ", "~", .) %>%
            toStringUnique
    }) %>% unlist
ortholog <- tibble(gene = raw[[1]], hsapiens = hsapiens)
rm(hsapiens,
   list,
   raw)
```



# RNAi phenotype

```{r rnaiPhenotype}
fileLocal <- file.path("data-raw",
                       "wormbase",
                       "rnai_phenotypes.tsv.gz")
if (!file.exists(fileLocal)) {
    # Improve this code using the `transmit()` function
    dir <- file.path("ftp://ftp.wormbase.org",
                     "pub",
                     "wormbase",
                     "releases",
                     "current-production-release",
                     "ONTOLOGY")
    fileRemote <- getURL(paste0(dir, "/"), dirlistonly = TRUE) %>%
        str_split("\n") %>%
        .[[1]] %>%
        str_subset("rnai_phenotypes_quick") %>%
        file.path(dir, .)
    fileLocal <- file.path("data-raw",
                           "wormbase",
                           "rnai_phenotypes.tsv")
    download.file(fileRemote, fileLocal)
    fileLocal <- gzip(fileLocal, overwrite = TRUE)
    rm(dir, fileRemote)
}
rnaiPhenotype <- read_tsv(
    fileLocal,
    col_names = c("gene",
                  "sequence",
                  "rnaiPhenotype")) %>%
    select(-sequence)
rm(fileLocal)
```



# BLASTP

```{r blastp}
import::from(biomaRt, getBM, useEnsembl)

# Wormpep IDs are used for BLASTP matching
fileLocal <- file.path("data-raw",
                       "wormbase",
                       "wormpep.tsv.gz")
if (!file.exists(fileLocal)) {
    dir <- file.path("ftp://ftp.wormbase.org",
                     "pub",
                     "wormbase",
                     "releases",
                     "current-production-release",
                     "species",
                     "c_elegans",
                     "PRJNA13758")
    fileRemote <- getURL(paste0(dir, "/"),
                         dirlistonly = TRUE) %>%
        str_split("\n") %>%
        .[[1]] %>%
        str_subset("wormpep_package") %>%
        as.character %>%
        file.path(dir, .)
    download.file(fileRemote, fileLocal)
    untar(fileLocal,
          exdir = file.path("data-raw", "wormbase"),
          files = "wormpep.table*")
    # Safe to delete the large source file
    unlink(fileLocal)
    fileLocal <- list.files(
        path = file.path("data-raw", "wormbase"),
        pattern = "wormpep.table",
        full.names = TRUE)
    fileRename <- file.path("data-raw",
                            "wormbase",
                            "wormpep.tsv")
    file.rename(fileLocal, fileRename)
    fileLocal <- fileRename
    fileLocal <- gzip(fileLocal, overwrite = TRUE)
    rm(fileRename)
}
wormpep <- read_lines(fileLocal) %>%
    str_split("\n") %>%
    mclapply(function(x) {
        gsub("^.*\t(CE[0-9]+\tWBGene[0-9]+).*$", "\\1", x) %>%
            str_split("\t") %>% .[[1]]
    }) %>%
    do.call(rbind, .) %>%
    as_tibble %>%
    setNames(c("wormpep", "gene"))

# Best BLASTP hits
bestBlastHits <- wormbaseAnnotationFile("best_blast_hits") %>%
    read_csv(col_names = FALSE) %>%
    select(X1, X4, X5) %>%
    rename(wormpep = X1,
           peptide = X4,
           eValue = X5) %>%
    filter(grepl("^ENSEMBL", peptide)) %>%
    mutate(peptide = str_sub(peptide, 9)) %>%
    left_join(wormpep, by = "wormpep")

# Map Ensembl peptide identifiers
hsapiens <- useEnsembl(
    biomart = "ensembl",
    dataset = "hsapiens_gene_ensembl")
hsapiensAnnotations <- getBM(
    mart = hsapiens,
    filters = "ensembl_peptide_id",
    values = bestBlastHits$peptide,
    attributes = c("ensembl_peptide_id",
                   "ensembl_gene_id",
                   "external_gene_name",
                   "description")) %>%
    rename(peptide = ensembl_peptide_id,
           hsapiensDescription = description,
           hsapiensGene = ensembl_gene_id,
           hsapiensName = external_gene_name)

# Final join
priorityCol <- c("gene", "eValue", "peptide", "wormpep")
blastp <- left_join(
    bestBlastHits, hsapiensAnnotations, by = "peptide") %>%
    # Place the priority columns first
    # one_of(priorityCol) also works with dplyr 0.6.0
    select(!!!syms(priorityCol), everything()) %>%
    group_by(gene) %>%
    arrange(!!!syms(priorityCol))
rm(bestBlastHits,
   fileLocal,
   hsapiens,
   hsapiensAnnotations,
   priorityCol,
   wormpep)
```



# Oligo

```{r oligo}
oligo <- wormbaseAnnotationFile("pcr_product2gene") %>%
    read_tsv(col_names = c("oligo", "gene")) %>%
    mutate(gene = str_extract(gene, "WBGene\\d{8}")) %>%
    group_by(gene)
```



# WormBase list

```{r wormbase}
wormbase <- list(
    gene = gene,
    description = description,
    blastp = blastp,
    ortholog = ortholog,
    rnaiPhenotype = rnaiPhenotype,
    oligo = oligo)
summary(wormbase)
lapply(wormbase, glimpse) %>% invisible
format(object.size(wormbase), units = "Mb")
use_data(wormbase, overwrite = TRUE)
```
