---
title: "rnaiLibrary function source data"
output: html_document
---

This must be run *after* sourcing the `metadata.Rmd` file.

```{r setup}
source("R/functions.R")
```

# ORFeome Library

Use the annotation data from [GE Dharmacon](http://dharmacon.gelifesciences.com/non-mammalian-cdna-and-orf/c.-elegans-rnai/):

## Convert the `orfeome.xlsx` source file

```{r orfeome}
orfeome <- list()
orfeome[["rawData"]] <- "data-raw/orfeome.xlsx"
if (!file.exists(orfeome$rawData)) {
  download.file("http://dharmacon.gelifesciences.com/uploadedFiles/Resources/cernai-feeding-library.xlsx",
                orfeome$rawData)
}
df <- readxl::read_excel(orfeome$rawData, sheet = 2)
colnames(df) <- seqcloudR::camel(colnames(df))

# Select the desired columns, rename, then subset the bad wells:
names(df)[names(df) == "orfIdWs112"] <- "orf"
df <- df[, c("orf", "plate", "row", "col")]
df <- subset(df, !is.na(orf))
df <- subset(df, orf != "no match in WS112")

# Set plate IDs as rownames
col <- c("plate", "row", "col")
cloneId <- do.call(paste, c(df[col], sep = "-"))
cloneId[1]
cloneId <- gsub("^(.*)-([0-9]{1})$", "\\1-0\\2", cloneId,
                  perl = TRUE, ignore.case = FALSE) # pad zeros
cloneId[1]
cloneId <- gsub("^([0-9]{5})-([A-Z]{1})-([0-9]{2})$", "\\1@\\2\\3", cloneId,
                  perl = TRUE, ignore.case = FALSE)
cloneId[1]
df <- cbind(cloneId, df)
rownames(df) <- df$cloneId

# Remove unnecessary columns
df$plate <- NULL
df$row <- NULL
df$col <- NULL

orfeome[["converted"]] <- df
devtools::use_data(orfeome, overwrite = TRUE)
```


# Ahringer Library

Use the annotation data from [Source Bioscience](http://www.us.lifesciences.sourcebioscience.com/clone-products/non-mammalian/c-elegans/c-elegans-rnai-library/):

```{r ahringer}
ahringer <- list()
ahringer[["rawData"]] <- "data-raw/ahringer.xlsx"
if (!file.exists(ahringer$rawData)) {
download.file("http://www.us.lifesciences.sourcebioscience.com/media/381254/C.%20elegans%20Database%202012.xlsx",
              ahringer$rawData)
}

chromosomes <- c("I", "II", "III", "IV", "V", "X")
for (i in 1:length(chromosomes)) {
  sheet <- i + 1 # First sheet contains notes
  df <- suppressWarnings(
    readxl::read_excel(ahringer$rawData, sheet = sheet)
    )
  colnames(df) <- seqcloudR::camel(colnames(df))

  # Drop wells from NA plates
  df <- subset(df, !is.na(plate))

  col <- c("chrom", "plate", "well")
  cloneId <- do.call(paste, c(df[col], sep = "-"))
  cloneId[1]
  cloneId <- gsub("^(.+)-(.+)-", "\\1-\\2@\\3", cloneId, perl = TRUE)
  cloneId[1]
  df <- cbind(cloneId, df)
  rownames(df) <- df$cloneId
  name <- paste0("chr", chromosomes[i])
  assign(name, df)
}
rm(df, i)
list <- list(chrI, chrII, chrIII, chrIV, chrV, chrX)
df <- data.frame(do.call("rbind", list))

# Remove unnecessary columns
df$extraInfo <- NULL
df$plate <- NULL
df$well <- NULL
df$chrom <- NULL

names(df)[names(df) == "genePairsName"] <- "orf"
ahringer[["converted"]] <- df
devtools::use_data(ahringer, overwrite = TRUE)
```
