---
title: "WormBase Description"
output: html_document
---

```{r setup}
library(readr)
source("wormbaseFtp.R")
```

```{r load}
wormbaseFile("functional_descriptions")
df <-
  read_delim(functionalDescriptions,
    delim = "\t",
    col_names = FALSE,
    skip = 4,
    # Column headers not properly tabbed
    na = c("", "none available", "not known")
  )
```

```{r colnames}
header <- read_lines(functionalDescriptions, n_max = 4)
header <- header[4]
header <- strsplit(header, " ")
colnames(df) <- header[[1]]
rm(header)

# Convert colnames to camel
colnames(df) <- camel(colnames(df))
```

```{r finishing touches}
# Make sure there's a valid identifier
df <- df[grepl("^WBGene[0-9]{8}$", df$geneId), ]
rownames(df) <- df$geneId

# Use duplicate columns from wormbaseGeneId instead
df$geneId <- NULL
df$publicName <- NULL
df$molecularName <- NULL

source("geneIdRows.R")
wormbaseDescription <- df
```

```{r save}
devtools::use_data(wormbaseDescription, overwrite = TRUE)
rm(df)
warnings()
```
