---
title: "EggNOG database annotations"
author: "`r getOption('author')`"
date: "`r Sys.Date()`"
---

```{r setup, message=FALSE}
source("setup.R")
eggnogDir <- file.path("data-raw", "eggnog")
dir.create(eggnogDir, recursive = TRUE, showWarnings = FALSE)
```

```{r header, child="_header.Rmd"}
```



```{r readme}
readme <- read_lines(
    file.path(
        "http://eggnogdb.embl.de",
        "download",
        "latest",
        "README.txt"))
writeLines(readme)
```



# Category

```{r category}
fileLocal <- file.path(eggnogDir, "category.txt")
download.file(
    url = file.path(
        "http://eggnogdb.embl.de",
        "download",
        "latest",
        "COG_functional_categories.txt"),
    destfile = fileLocal)
pattern <- "^\\s\\[([A-Z])\\]\\s([A-Za-z\\s]+)\\s$"
category <- fileLocal %>%
    readLines() %>%
    str_subset(pattern) %>%
    str_match(pattern) %>%
    as_tibble() %>%
    select(-1) %>%
    set_names(c("letter", "description")) %>%
    arrange(letter)
glimpse(category)
```



# Annotation

```{r}
colnames <- c(
    "taxonomicLevel",
    "groupName",
    "proteinCount",
    "speciesCount",
    "cogFunctionalCategory",
    "consensusFunctionalDescription")
```


## EUNOG: Eukaryota

```{r eunog}
fileLocal <- file.path(eggnogDir, "eunog.tsv.gz")
download.file(
    file.path(
        "http://eggnogdb.embl.de",
        "download",
        "latest",
        "data",
        "euNOG",
        "euNOG.annotations.tsv.gz"),
    fileLocal)
eunog <- read_tsv(fileLocal, col_names = colnames)
```


## NOG: LUCA

```{r nog}
fileLocal <- file.path(eggnogDir, "nog.tsv.gz")
download.file(
    url = file.path(
        "http://eggnogdb.embl.de",
        "download",
        "latest",
        "data",
        "NOG",
        "NOG.annotations.tsv.gz"),
    destfile = fileLocal)
nog <- read_tsv(fileLocal, col_names = colnames)
```

```{r annotation}
annotation <- bind_rows(eunog, nog) %>%
    select(
        groupName,
        consensusFunctionalDescription,
        cogFunctionalCategory
    ) %>%
    rename(eggnog = groupName)
glimpse(annotation)
```



# Save

```{r save_data}
eggnog <- list(
    annotation = annotation,
    category = category)
saveData(eggnog, dir = dataDir, compress = compress)
rm(annotation,
   category,
   colnames,
   eunog,
   fileLocal,
   nog,
   pattern)
```



```{r footer, child="_footer.Rmd"}
```
