---
title: "RNAi annotations"
date: "`r BiocStyle::doc_date()`"
---

```{r setup, include=FALSE}
source("setup.R")
```

```{r header, child="header.Rmd"}
```



# [WORFDB][]

```{r functions}
worfdbHtml <- function(sequence) {
    sequence <- sequence %>% na.omit %>% unique
    pbmclapply(seq_along(sequence), function(a) {
        GET(paste0("http://worfdb.dfci.harvard.edu/searchallwormorfs.pl?by=name&sid=",
                   sequence[a]),
            user_agent = user_agent(ua)) %>%
            content("text")
    }) %>% setNames(sequence)
}

worfdbData <- function(worfdbHtml) {
    pbmclapply(seq_along(worfdbHtml), function(a) {
        html <- worfdbHtml[[a]] %>%
            # Remove `<map>` that has other clone information
            # This messes up well identifier matching otherwise
            gsub("<map.+</map>", "", .)
        clone <- html %>%
            str_extract_all("[0-9]{5}@[A-H][0-9]+") %>%
            unlist %>%
            toStringUnique
        inFrame <- html %>%
            str_extract_all("In Frame.+<font color=black>([NY])</font>") %>%
            unlist %>%
            str_replace("&nbsp;<font color=black>([NY])</font>", "\\1") %>%
            str_replace_all("Y$", TRUE) %>%
            str_replace_all("N$", FALSE) %>%
            toStringUnique
        sequence <- html %>%
            str_match_all("<A HREF=http://www.wormbase.org/db/seq/sequence\\?name=([A-Za-z0-9\\.]+)>") %>%
            .[[1]] %>% .[, 2] %>%
            # Strip isoform
            gsub("[a-z]$", "", .) %>%
            toStringUnique
        sequencingInformation <- html %>%
            str_extract_all("OST in ORFeome version.+\\(WS[0-9]+\\)") %>%
            unlist %>%
            toStringUnique
        primer <- html %>%
            str_match_all("<font color=red><B>([acgt]+)[\n]?</B></font>") %>%
            .[[1]] %>% .[, 2] %>%
            toupper %>%
            toString
        size <- html %>%
            str_match_all("size: &nbsp;([0-9]+)") %>%
            .[[1]] %>% .[, 2] %>%
            toString
        remap <- html %>%
            str_match_all("<TR><TD><A HREF=searchallwormorfs.pl\\?sid=([A-Z0-9]+\\.[0-9]+[a-z]?)>[A-Z0-9]+\\.[0-9]+[a-z]?</A></TD><TD>([0-9]{5}@[A-H][0-9]+)</TD><TD>([0-9]{5}@[A-H][0-9]+)?</TD><TD>(N|Y)</TD><TD>([0-9]+)</TD></TR>") %>%
            .[[1]] %>% .[, 2] %>%
            basejump::toStringUnique(.)
        list <- list(query = names(worfdbHtml)[a],
                     sequence = sequence,
                     clone = clone,
                     sequencingInformation = sequencingInformation,
                     inFrame = inFrame,
                     primer = primer,
                     remap = remap,
                     size = size)
        lapply(list, function(b) {
            as_tibble(Filter(Negate(is.null), b))
        })
    }) %>%
        bind_rows %>%
        wash %>%
        arrange(sequence) %>%
        filter(!is.na(clone)) %>%
        mutate(clone = str_replace(clone, "@", ""),
               clone = str_replace(clone, "([A-Z]{1})0", "\\1")) %>%
        left_join(gene(.$sequence,
                       format = "sequence",
                       select = "gene"),
                  by = "sequence")
}
```

```{r worfdb1}
file <- file.path("data-raw", "worfdb", "worfdbHtml.rda")
if (!file.exists(file)) {
    data(wormbaseGene)
    sequence <- wormbaseGene$sequence
    worfdbHtml <- worfdbHtml(sequence)
    save(worfdbHtml, file = file)
} else {
    load(file)
}
rm(file)
worfdb1 <- worfdbData(worfdbHtml)
```

```{r worfdb2}
file <- file.path("data-raw", "worfdb", "worfdbHtmlRemap.rda")
if (!file.exists(file)) {
    # Example: H15N14.1
    sequenceRemap <- worfdb1 %>%
        filter(!is.na(remap)) %>%
        select(remap) %>%
        toString %>%
        str_split(", ") %>%
        unlist
    worfdbHtmlRemap <- worfdbHtml(sequenceRemap)
    save(worfdbHtmlRemap, file = file)
} else {
    load(file)
}
rm(file)
worfdbRemap <- worfdbData(worfdbHtmlRemap)
```

```{r worfdb_join}
worfdb <- bind_rows(worfdb, worfdbRemap) %>%
    filter(is.na(remap)) %>%
    select(-c(query, remap)) %>%
    distinct %>%
    arrange(clone)
# Check for duplicates
dupes <- worfdb %>%
    group_by(clone) %>%
    filter(n() > 1) %>%
    select(clone, everything())
```



# Ahringer library

```{r sourcebioscience, eval=FALSE}
fileLocal <- file.path("data-raw", "sourcebioscience.xlsx")
download.file("http://www.us.lifesciences.sourcebioscience.com/media/381254/C.%20elegans%20Database%202012.xlsx", fileLocal)
chromosomes <- c("I", "II", "III", "IV", "V", "X")
list <- mclapply(seq_along(chromosomes), function(a) {
    # Note that the first sheet contains notes, so `i + 1`
    read_excel(fileLocal,
               sheet = a + 1,
               col_types = rep("text", 8))
}) %>% setNames(chromosomes)
lapply(list, glimpse) %>% invisible
input <- bind_rows(list) %>%
    setNamesCamel %>%
    filter(!grepl("mismatch", extraInfo)) %>%
    rename(genePair = genePairsName,
           clone384 = sourceBioscienceLocation) %>%
    mutate(clone96 = paste0(plate, well),
           clone96 = str_replace(clone96, "([A-Z]{1})0", "\\1"),
           clone384 = str_replace(clone384, "-", ""),
           clone384 = str_replace(clone384, "([A-Z]{1})0", "\\1"),
           fwdPrimerSeq = toupper(fwdPrimerSeq),
           revPrimerSeq = toupper(revPrimerSeq)) %>%
    select(-c(chrom, extraInfo, plate, well)) %>%
    arrange(genePair, clone384) %>%
    select(noquote(order(names(.))))
glimpse(input)

# Match `genePair` against `sequence` with `gene()` function
matched <- list()
matched$sequence <- input %>%
    mutate(sequence = str_replace(genePair,
                                  "^([A-Z0-9]+\\.[0-9]+)[a-z]$",
                                  "\\1")) %>%
    # Note that this depends on `gene()` from the package
    left_join(gene(.$sequence,
                   format = "sequence",
                   select = "gene"),
              by = "sequence") %>%
    filter(!is.na(gene))
unmatched <- input %>%
    filter(!genePair %in% matched[["sequence"]][["genePair"]])
nrow(matched$sequence)
nrow(unmatched)

# Match by `sjj_` oligo:
data(wormbaseOligo)
matched$oligo <- unmatched %>%
    mutate(oligo = paste0("sjj_", genePair)) %>%
    left_join(wormbaseOligo, by = "oligo") %>%
    filter(!is.na(gene))
unmatched <- unmatched %>%
    filter(!genePair %in% matched[["oligo"]][["genePair"]])
nrow(matched$oligo)
nrow(unmatched)

# Match by `sjj2_` oligo:
matched$oligo2 <- unmatched %>%
    mutate(oligo = paste0("sjj2_", genePair)) %>%
    left_join(wormbaseOligo, by = "oligo") %>%
    filter(!is.na(gene))
unmatched <- unmatched %>%
    filter(!genePair %in% matched[["oligo2"]][["genePair"]])
nrow(matched$oligo2)
nrow(unmatched)

sourcebioscience <- bind_rows(matched, unmatched)
use_data(sourcebioscience, overwrite = TRUE)
rm(chromosomes,
   fileLocal,
   list,
   input,
   matched,
   unmatched)
```



# Cherrypick libraries

```{r cherrypick}
cherrypick <- file.path("data-raw", "cherrypick.xlsx") %>%
    read_excel %>%
    mutate(clone = paste0(library,
                          plateNum,
                          plateRow,
                          plateCol)) %>%
    filter(!is.na(sequence)) %>%
    select(clone, sequence) %>%
    arrange(clone) %>%
    # Depends upon gene function
    left_join(gene(.$sequence, format = "sequence"), by = "sequence")
```



# RNAi list

```{r rnai}
dataRaw(c("cherrypick", "sourcebioscience", "worfdb"))
cherrypick <- cherrypick %>%
    select(gene, sequence, clone) %>%
    filter(!is.na(gene)) %>%
    rename(genePair = sequence)
sourcebioscience <- sourcebioscience %>%
    rowwise %>%
    mutate(clone = toString(c(clone384, clone96))) %>%
    select(gene, genePair, clone)
worfdb <- worfdb %>%
    select(gene, sequence, clone) %>%
    rename(genePair = sequence)
rnai <- bind_rows(cherrypick,
                  sourcebioscience,
                  worfdb) %>%
    filter(!is.na(gene)) %>%
    group_by(gene) %>%
    toStringSummarize %>%
    left_join(gene(.$gene, select = "biotype"), by = "gene") %>%
    select(noquote(order(names(.))))
rm(cherrypick, sourcebioscience, worfdb)
```
