---
title: "WORFDB"
date: "`r BiocStyle::doc_date()`"
---

```{r setup, include=FALSE}
source("setup.R")
```

```{r header, child="header.Rmd"}
```

```{r functions}
worfdbHtml <- function(sequence) {
    sequence <- sequence %>% na.omit %>% unique
    pbmclapply(seq_along(sequence), function(a) {
        GET(paste0("http://worfdb.dfci.harvard.edu/searchallwormorfs.pl?by=name&sid=",
                   sequence[a]),
            user_agent = user_agent(ua)) %>%
            content("text")
    }) %>% setNames(sequence)
}

worfdbData <- function(worfdbHtml) {
    pbmclapply(seq_along(worfdbHtml), function(a) {
        html <- worfdbHtml[[a]] %>%
            # Remove `<map>` that has other clone information
            # This messes up well identifier matching otherwise
            gsub("<map.+</map>", "", .)
        clone <- html %>%
            str_extract_all("[0-9]{5}@[A-H][0-9]+") %>%
            unlist %>%
            toStringUnique
        inFrame <- html %>%
            str_extract_all("In Frame.+<font color=black>([NY])</font>") %>%
            unlist %>%
            str_replace("&nbsp;<font color=black>([NY])</font>", "\\1") %>%
            str_replace_all("Y$", TRUE) %>%
            str_replace_all("N$", FALSE) %>%
            toStringUnique
        sequence <- html %>%
            str_match_all("<A HREF=http://www.wormbase.org/db/seq/sequence\\?name=([A-Za-z0-9\\.]+)>") %>%
            .[[1]] %>% .[, 2] %>%
            # Strip isoform
            gsub("[a-z]$", "", .) %>%
            toStringUnique
        sequencingInformation <- html %>%
            str_extract_all("OST in ORFeome version.+\\(WS[0-9]+\\)") %>%
            unlist %>%
            toStringUnique
        primer <- html %>%
            str_match_all("<font color=red><B>([acgt]+)[\n]?</B></font>") %>%
            .[[1]] %>% .[, 2] %>%
            toupper %>%
            toString
        size <- html %>%
            str_match_all("size: &nbsp;([0-9]+)") %>%
            .[[1]] %>% .[, 2] %>%
            toString
        remap <- html %>%
            str_match_all("<TR><TD><A HREF=searchallwormorfs.pl\\?sid=([A-Z0-9]+\\.[0-9]+[a-z]?)>[A-Z0-9]+\\.[0-9]+[a-z]?</A></TD><TD>([0-9]{5}@[A-H][0-9]+)</TD><TD>([0-9]{5}@[A-H][0-9]+)?</TD><TD>(N|Y)</TD><TD>([0-9]+)</TD></TR>") %>%
            .[[1]] %>% .[, 2] %>%
            basejump::toStringUnique(.)
        list <- list(query = names(worfdbHtml)[a],
                     sequence = sequence,
                     clone = clone,
                     sequencingInformation = sequencingInformation,
                     inFrame = inFrame,
                     primer = primer,
                     remap = remap,
                     size = size)
        lapply(list, function(b) {
            as_tibble(Filter(Negate(is.null), b))
        })
    }) %>%
        bind_rows %>%
        arrange(sequence) %>%
        filter(!is.na(clone)) %>%
        mutate(clone = str_replace(clone, "@", ""),
               clone = str_replace(clone, "([A-Z]{1})0", "\\1")) %>%
        left_join(gene(.$sequence,
                       format = "sequence",
                       select = "gene"),
                  by = "sequence")
}
```



```{r worfdb1}
file <- file.path("data-raw", "worfdb", "worfdbHtml.rda")
if (!file.exists(file)) {
    data(wormbaseGene)
    sequence <- wormbaseGene$sequence
    worfdbHtml <- worfdbHtml(sequence)
    save(worfdbHtml, file = file)
} else {
    load(file)
}
rm(file)
worfdb1 <- worfdbData(worfdbHtml)
```

```{r worfdb2}
file <- file.path("data-raw", "worfdb", "worfdbHtmlRemap.rda")
if (!file.exists(file)) {
    # Example: H15N14.1
    sequenceRemap <- worfdb1 %>%
        filter(!is.na(remap)) %>%
        select(remap) %>%
        toString %>%
        str_split(", ") %>%
        unlist
    worfdbHtmlRemap <- worfdbHtml(sequenceRemap)
    save(worfdbHtmlRemap, file = file)
} else {
    load(file)
}
rm(file)
worfdbRemap <- worfdbData(worfdbHtmlRemap)
```

```{r worfdb_join}
worfdb <- bind_rows(worfdb, worfdbRemap) %>%
    filter(is.na(remap)) %>%
    select(-c(query, remap)) %>%
    distinct %>%
    arrange(clone)
# Check for duplicates
dupes <- worfdb %>%
    group_by(clone) %>%
    filter(n() > 1) %>%
    select(clone, everything())
```



```{r footer, child="footer.Rmd"}
```
