---
title: "Ahringer clone annotations"
date: "`r BiocStyle::doc_date()`"
---

```{r setup, message=FALSE}
source("setup.R")
loadData(geneIDs, oligo)
```

```{r header, child="header.Rmd"}
```



# Import the raw data

```{r list}
fileLocal <- "data-raw/ahringer.xlsx"
if (!file.exists(fileLocal)) {
    download.file(file.path(
    "http://www.us.lifesciences.sourcebioscience.com",
    "media",
    "381254",
    "C.%20elegans%20Database%202012.xlsx"), fileLocal)
}
chromosomes <- c("I", "II", "III", "IV", "V", "X")
list <- mclapply(seq_along(chromosomes), function(a) {
    # Note that the first sheet contains notes, so `i + 1`
    read_excel(fileLocal,
               sheet = a + 1,
               col_types = rep("text", 8))
}) %>% set_names(chromosomes)
lapply(list, glimpse)
```

```{r input}
input <- bind_rows(list) %>%
    camel %>%
    filter(!grepl("mismatch", extraInfo)) %>%
    rename(genePair = genePairsName,
           clone384 = sourceBioscienceLocation) %>%
    mutate(clone96 = paste0(plate, well),
           fwdPrimerSeq = toupper(fwdPrimerSeq),
           revPrimerSeq = toupper(revPrimerSeq)) %>%
    select(-c(chrom, extraInfo, plate, well)) %>%
    arrange(genePair, clone384) %>%
    select(noquote(order(names(.))))
glimpse(input)
```



# Match against [WormBase][]

```{r matching}
# Match `genePair` against `sequence` with `geneIDs` data frame
matched <- list()
matched$sequence <- input %>%
    mutate(sequence = str_replace(
        genePair, "^([A-Z0-9]+\\.[0-9]+)[a-z]$", "\\1")) %>%
    left_join(geneIDs[, c("gene", "sequence")], by = "sequence") %>%
    filter(!is.na(gene))
unmatched <- input %>%
    filter(!genePair %in% matched$sequence$genePair)
nrow(matched$sequence)
nrow(unmatched)

# Match by `sjj_` oligo:
matched$oligo <- unmatched %>%
    mutate(oligo = paste0("sjj_", genePair)) %>%
    left_join(oligo, by = "oligo") %>%
    filter(!is.na(gene))
unmatched <- unmatched %>%
    filter(!genePair %in% matched$oligo$genePair)
nrow(matched$oligo)
nrow(unmatched)

# Match by `sjj2_` oligo:
matched$oligo2 <- unmatched %>%
    mutate(oligo = paste0("sjj2_", genePair)) %>%
    left_join(oligo, by = "oligo") %>%
    filter(!is.na(gene))
unmatched <- unmatched %>%
    filter(!genePair %in% matched$oligo2$genePair)
nrow(matched$oligo2)
nrow(unmatched)

ahringer <- bind_rows(matched, unmatched)
saveData(ahringer, dir = dataDir, compress = compress)

rm(chromosomes,
   fileLocal,
   list,
   input,
   matched,
   unmatched)
```



```{r footer, child="footer.Rmd"}
```
