---
title: "WormBase BLASTP Matches"
output: html_document
---

```{r setup}
library(biomaRt)
library(plyr)
library(R.utils)
library(readr)
source("wormbaseFtp.R")
```

```{r blastp import}
# Get the highest match for each peptide
wormbaseFile("best_blast_hits")
input <- read_csv(bestBlastHits, col_names = FALSE)
df <- input[, c(1, 4, 5)]
colnames(df) <- c("wormpepId",
                  "ensemblPeptideId",
                  "eValue")

# Filter for only ENSEMBL info
df <- df[grepl("ENSEMBL", df$ensemblPeptideId), ]

# Remove "ENSEMBL:" from column
df$ensemblPeptideId <- substr(df$ensemblPeptideId, 9, 23)

# Sort by E value to get the highest confidence BLASTP match
df <- df[order(df$wormpepId, df$eValue), ]

# Now remove duplicates, will which eliminate the lower confidence entries
df <- df[!duplicated(df$wormpepId), ]
rownames(df) <- as.vector(df$wormpepId)
blastpScores <- df
```

Wormpep IDs are used for BLASTP matching:

```{r wormpep download}
dir <- "ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/"
ls <- getURL(dir, dirlistonly = TRUE)
ls <- strsplit(ls, "\n")
ls <- ls[[1]]
grep <- grep("wormpep_package", ls, value = TRUE)
file <- paste0(dir, grep)
download.file(file, "wormpep.tar.gz")

# Extract wormpep.table specifically -- works on macOS
system("tar -xzf wormpep.tar.gz wormpep.table*")
file <- list.files(pattern = "wormpep.table")
file.rename(file, file.path("data-raw", "wormpep.txt"))
file.remove("wormpep.tar.gz")
```

```{r mapping}
input <- read_lines(file.path("data-raw", "wormpep.txt"))
input <- strsplit(input, "\n")
wormpep <- lapply(input, function(x) {
  x <- gsub("^.*\t(CE[0-9]+\tWBGene[0-9]+).*$", "\\1", x, perl = T)
  y <- strsplit(x, "\t")
  x <- y[[1]]
})
head(wormpep)
df <- data.frame(do.call("rbind", wormpep))
rm(wormpep)
colnames(df) <- c("wormpepId", "geneId")
wormpepId <- df
```

```{r match e values}
vec <- as.vector(wormpepId$wormpepId)
ensembl <- blastpScores[vec, c("ensemblPeptideId", "eValue")]
df <- cbind(df, ensembl)
rm(ensembl, vec)
# Subset only the top blastp with ensembl match
df <- df[order(df$geneId, df$eValue, df$wormpepId), ]
df <- df[!duplicated(df$geneId), ]
df <- df[!is.na(df$ensemblPeptideId), ]
rownames(df) <- df$geneId
# Clean up the names for binding
df$geneId <- NULL
blastpGeneId <- df
rm(df)
```

```{r biomart human orthologs}
ensemblPeptideId <- as.vector(blastpGeneId$ensemblPeptideId)
mart <- useMart("ensembl", "hsapiens_gene_ensembl")
biomartOptions <- listAttributes(mart)
df <- getBM(mart = mart,
            filters = "ensembl_peptide_id",
            values = ensemblPeptideId,
            attributes = c("ensembl_peptide_id",
                           "ensembl_gene_id",
                           "external_gene_name",
                           "description"))
colnames(df)[colnames(df) == "external_gene_name"] <- "ensembl_gene_name"
colnames(df)[colnames(df) == "description"] <- "ensembl_description"
colnames(df) <- toCamelCase(colnames(df), split = "_")
rownames(df) <- df$ensemblPeptideId
df$ensemblPeptideId <- NULL
df <- df[ensemblPeptideId, ]
df <- cbind(blastpGeneId, df)
```

```{r save}
source("geneIdRows.R")
wormbaseBlastp <- df
devtools::use_data(wormbaseBlastp, overwrite = TRUE)
```
