---
title: "WORFDB annotations"
date: "`r BiocStyle::doc_date()`"
---

```{r setup, message=FALSE}
source("setup.R")
loadData(
    geneIDs,
    worfdbHTML,
    worfdbHTMLRemap,
    dir = dataDir)
```

```{r header, child="_header.Rmd"}
```



```{r worfdb}
# FIXME R153.1f
# FIXME 30037@G9, 30040@G2

worfdbList1 <- worfdbList(worfdbHTML)
worfdbData1 <- worfdbData(worfdbList1)

worfdbList2 <- worfdbList(worfdbHTMLRemap)
worfdbData2 <- worfdbData(worfdbList2)

# Add step for filtering bad sequence?
worfdb <- bind_rows(worfdbData1, worfdbData2) %>%
    fixNA() %>%
    filter(is.na(remap)) %>%
    select(-c(query, remap)) %>%
    distinct() %>%
    mutate(
        # Remove `@`
        clone = gsub(x = .data[["clone"]],
                     pattern = "@",
                     replacement = ""),
        # Remove leading zero in well
        clone = gsub(x = .data[["clone"]],
                     pattern = "([A-Z]{1})0",
                     replacement = "\\1")
    ) %>%
    arrange(clone) %>%
    left_join(geneIDs[, c("gene", "sequence")], by = "sequence")
saveData(worfdb, dir = dataDir, compress = compress)
```

Check for unmatched clones:

```{r unmatched}
unmatched <- filter(worfdb, is.na(gene))
unmatched
```

Check for duplicate sequences:

```{r dupes}
dupes <- worfdb %>%
    group_by(clone) %>%
    filter(n() > 1) %>%
    select(clone, everything())
dupes
```



```{r footer, child="_footer.Rmd"}
```
