---
title: "ORFeome RNAi library"
output: html_document
---

```{r setup}
library(RCurl)
library(readr)
library(readxl)
library(seqcloudR)
load("data/metadataOrf.rda")
source("getOrfMetadata.R")
```

## Download and setup Excel file

### Download

Use the metadata from [GE Dharmacon](http://dharmacon.gelifesciences.com/non-mammalian-cdna-and-orf/c.-elegans-rnai/):

```{r download}
download.file("http://dharmacon.gelifesciences.com/uploadedFiles/Resources/cernai-feeding-library.xlsx",
              "data-raw/orfeome.xlsx")
xlsx <- read_excel("data-raw/orfeome.xlsx", sheet = 2)
colnames(xlsx) <- camel(colnames(xlsx))
```

### Filter

```{r filter}
# Select the desired columns and rename
df <- xlsx
names(df)[names(df) == "orfIdWs112"] <- "orfOriginal"
df <- df[, c("orfOriginal", "plate", "row", "col")]

# Subset the bad wells
df <- subset(df, !is.na(orfOriginal))
df <- subset(df, orfOriginal != "no match in WS112")
xlsxFiltered <- df
```

### cloneId

Set plate IDs as rownames:

```{r cloneId}
df <- xlsxFiltered
col <- c("plate", "row", "col")
cloneId <- do.call(paste, c(df[col], sep = "-"))
cloneId[1]
cloneId <- gsub("^(.*)-([0-9]{1})$", "\\1-0\\2", cloneId,
                  perl = TRUE, ignore.case = FALSE) # pad zeros
cloneId[1]
cloneId <- gsub("^([0-9]{5})-([A-Z]{1})-([0-9]{2})$", "\\1@\\2\\3", cloneId,
                  perl = TRUE, ignore.case = FALSE)
cloneId[1]
df <- cbind(cloneId, df)
rownames(df) <- df$cloneId
xlsxConverted <- df
```

## Update metadata

```{r metadata}
orf2GeneId <- getOrfMetadata(as.vector(xlsxConverted$orfOriginal))

# Bind the matches back to the orfeomeValid data frame
df <- xlsxConverted[, c("cloneId", "orfOriginal")]

# Now we can bind the metadata
df <- cbind(df, orf2GeneId)
rownames(df) <- as.vector(df$cloneId)
colnames(df)

# Unmapped ORFs
unmappedOrf <- subset(df, is.na(geneId))
unmappedOrf <- unmappedOrf[, 1:2]

# Remove them from main df, we'll add back later
df <- subset(df, !is.na(geneId))

# Get the ORF merge mappings
orfMergeInput <- read_excel("orfMerge.xlsx", sheet = 1, na = "NA")

rownames(orfMergeInput) <- orfMergeInput$cloneId
orfMergeInput <- orfMergeInput[rownames(unmappedOrf), ]
rownames(orfMergeInput) <- rownames(unmappedOrf)

# Get the metadata of these merged ORFs
orf2GeneIdMerge <- getOrfMetadata(as.vector(orfMergeInput$mergedOrf))

# Bind back to main data frame
orfMerge <- cbind(unmappedOrf, orf2GeneIdMerge)
df <- rbind(df, orfMerge)
df <- df[rownames(xlsxConverted), ]

# Add back the complete metadata
df <- cbind(xlsxConverted, df)
# Remove duplicate columns
df <- df[, unique(colnames(df))]

# Additional information for library troubleshooting
debugNoGeneId <- df[is.na(df$geneId), ]
debugUnique <- unique(as.vector(df$orf))
```

```{r save}
orfeome <- df
devtools::use_data(orfeome, overwrite = TRUE)
warnings()
```
