---
title: "Cherrypick RNAi library annotations"
date: "`r BiocStyle::doc_date()`"
---

```{r setup}
source("setup.R")
```

```{r gene}
loadData(
    geneIDs,
    geneOtherIDs,
    description,
    ortholog,
    rnaiPhenotype,
    panther,
    dir = "data")
# FIXME Need to prefix panther columns
gene <- Reduce(
    f = function(...) left_join(..., by = "gene"),
    x = list(geneIDs,
             geneOtherIDs,
             description,
             ortholog,
             rnaiPhenotype,
             panther)
) %>%
    as_tibble() %>%
    mutate(descriptionDetailed = NULL,
           uniprotKB = NULL) %>%
    # select(noquote(order(names(.)))) %>%
    # select(gene, everything()) %>%
    arrange(gene)
```

```{r rnai}
loadData(ahringer, cherrypick, worfdb)
ahringer <- ahringer %>%
    # rowwise %>%
    # [fix] mutate is crashing R?
    # Simply use toString?
    # mutate(clone = str_c(clone384, clone96, collapse = ", ")) %>%
    select(gene, genePair, clone384, clone96)
worfdb <- worfdb %>%
    select(gene, sequence, clone) %>%
    rename(genePair = sequence)
rnai <- bind_rows(ahringer, cherrypick, worfdb) %>%
    filter(!is.na(gene)) %>%
    group_by(gene) %>%
    summarizeRows %>%
    select(gene, noquote(order(names(.))))
```

```{r eggnog}
loadData(eggnog)
```

```{r peptide}
loadData(blastp, peptide)
```

```{r build}
wormbase <- getURL("ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/",
                   dirlistonly = TRUE) %>%
    str_extract("WS[0-9]{3}") %>%
    paste0("WormBase ", .)
ensembl <- listMarts(host = "useast.ensembl.org") %>%
    filter(biomart == "ENSEMBL_MART_ENSEMBL") %>%
    select(version) %>% .[[1]]
panther <- getURL("ftp://ftp.pantherdb.org/sequence_classifications/current_release/PANTHER_Sequence_Classification_files/",
                  dirlistonly = TRUE) %>%
    str_extract("(\\d{2}\\.\\d)") %>%
    paste0("PANTHER ", .)
rstats <- paste0(R.Version()$version.string,
                 " running on ",
                 R.Version()$platform)
build <- list(date = Sys.Date(),
              ensembl = ensembl,
              panther = panther,
              rstats = rstats,
              wormbase = wormbase,
              sessionInfo = sessionInfo)
```

```{r annotations}
annotations <- list(
    gene = gene,
    rnai = rnai,
    eggnog = eggnog,
    blastp = blastp,
    peptide = peptide,
    build = build
)
saveData(annotations)
```
