---
title: "Cherrypick RNAi library annotations"
date: "`r BiocStyle::doc_date()`"
---

```{r setup, message=FALSE}
source("setup.R")
```

```{r render}
render("01_wormbase.Rmd")
render("02_panther.Rmd")
render("03_eggnog.Rmd")
render("04_worfdb.Rmd")
render("05_ahringer.Rmd")
render("06_cherrypick.Rmd")
```

```{r load}
loadData(
    ahringer,
    blastp,
    cherrypick,
    eggnog,
    geneIDs,
    geneOtherIDs,
    description,
    ortholog,
    panther,
    peptide,
    rnaiPhenotype,
    worfdb,
    dir = dataDir)
```

```{r prefix_panther}
panther <- panther %>%
    set_colnames(
        camel(paste("panther", colnames(.), sep = "_"), strict = FALSE)
    ) %>%
    rename(gene = pantherGene)
```

```{r gene}
gene <- Reduce(
    f = function(...) left_join(..., by = "gene"),
    x = list(geneIDs,
             geneOtherIDs,
             description,
             ortholog,
             rnaiPhenotype,
             panther)
) %>%
    as_tibble() %>%
    mutate(descriptionDetailed = NULL,
           uniprotKB = NULL) %>%
    select(noquote(order(names(.)))) %>%
    select(gene, everything()) %>%
    arrange(gene)
```

```{r rnai}
ahringer_bind <- ahringer %>%
    select(gene, genePair, clone384, clone96) %>%
    rename(ahringer384 = clone384,
           ahringer96 = clone96)
worfdb_bind <- worfdb %>%
    select(gene, sequence, clone) %>%
    rename(genePair = sequence,
           worfdb96 = clone)
cherrypick_bind <- cherrypick %>%
    select(gene, sequence, clone) %>%
    rename(genePair = sequence,
           cherrypick96 = clone)
rnai <- bind_rows(ahringer_bind, cherrypick_bind, worfdb_bind) %>%
    filter(!is.na(gene)) %>%
    group_by(gene) %>%
    collapseToString(sort = TRUE, unique = TRUE) %>%
    select(gene, noquote(order(names(.))))
```

```{r build}
wormbase <- file.path(
    "ftp://ftp.wormbase.org",
    "pub",
    "wormbase",
    "releases",
    "current-production-release",
    "ONTOLOGY") %>%
    getURL(paste0(., "/"), dirlistonly = TRUE) %>%
    str_extract("WS\\d{3}") %>%
    paste0("WormBase ", .)
ensembl <- listMarts(host = "useast.ensembl.org") %>%
    filter(biomart == "ENSEMBL_MART_ENSEMBL") %>%
    select(version) %>%
    .[[1]]
panther <- file.path(
    "ftp://ftp.pantherdb.org",
    "sequence_classifications",
    "current_release",
    "PANTHER_Sequence_Classification_files") %>%
    paste0(., "/") %>%
    getURL(dirlistonly = TRUE) %>%
    str_extract("(\\d{2}\\.\\d)") %>%
    paste0("PANTHER ", .)
rstats <- paste0(
    R.Version()$version.string,
    " running on ",
    R.Version()$platform)
build <- list(
    date = Sys.Date(),
    ensembl = ensembl,
    panther = panther,
    wormbase = wormbase,
    rstats = rstats,
    sessionInfo = sessionInfo)
```

```{r save}
worminfo <- list(
    gene = gene,
    rnai = rnai,
    eggnog = eggnog,
    blastp = blastp,
    peptide = peptide,
    build = build)
saveData(worminfo, dir = "data", compress = "xz")
```
