---
title: "EggNOG database annotations"
date: "`r BiocStyle::doc_date()`"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_package_root_file())
knitr::opts_chunk$set(cache = TRUE)
```

```{r dir}
if (!file.exists("data-raw/eggnog")) {
    dir.create("data-raw/eggnog", recursive = TRUE)
}
```



# README

```{r readme}
download.file("http://eggnogdb.embl.de/download/latest/README.txt",
              "data-raw/eggnog/README.txt")
colNames <- c("taxonomicLevel",
              "groupName",
              "proteinCount",
              "speciesCount",
              "cogFunctionalCategory",
              "consensusFunctionalDescription")
```



# Category

```{r category}
download.file("http://eggnogdb.embl.de/download/latest/COG_functional_categories.txt",
              "data-raw/eggnog/category.txt")
category <- readLines("data-raw/eggnog/category.txt") %>%
    .[grepl("^\\s\\[", .)] %>%
    # Strip leading and trailing spaces:
    gsub("^\\s|\\s$", "", .) %>%
    stringr::str_match(., "^\\[([A-Z])\\]\\s(.+)$") %>%
    .[, 2:3] %>%
    tibble::as_tibble(.) %>%
    stats::setNames(., c("cogFunctionalCategory",
                         "cogFunctionalDescription")) %>%
    dplyr::arrange(cogFunctionalCategory)
```



# Annotation

## EUNOG: Eukaryota

```{r eunog}
download.file("http://eggnogdb.embl.de/download/latest/data/euNOG/euNOG.annotations.tsv.gz",
              "data-raw/eggnog/eunog.tsv.gz")
eunog <- readr::read_tsv("data-raw/eggnog/eunog.tsv.gz", col_names = colNames)
```


## NOG: LUCA (All organisms)

```{r nog}
download.file("http://eggnogdb.embl.de/download/latest/data/NOG/NOG.annotations.tsv.gz",
              "data-raw/eggnog/nog.tsv.gz")
nog <- readr::read_tsv("data-raw/eggnog/nog.tsv.gz", col_names = colNames)
```



# Final assembly

```{r final_assembly}
annotation <- dplyr::bind_rows(eunog, nog) %>%
    dplyr::select(groupName,
                  consensusFunctionalDescription,
                  cogFunctionalCategory) %>%
    dplyr::rename(eggnog = groupName)
eggnog <- list(annotation = annotation,
               category = category)
devtools::use_data(eggnog, overwrite = TRUE)
rm(annotation,
   category,
   eunog,
   nog)
```
