---
title: "ORFeome RNAi library annotations"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath("../"))
```

```{r, eval=FALSE, include=FALSE}
rm(list = setdiff(ls(), lsf.str()))
rm(list = ls())
seqcloudr::loadpkg()
```

# ORFeome Library

Use the annotation data from [GE Dharmacon](http://dharmacon.gelifesciences.com/non-mammalian-cdna-and-orf/c.-elegans-rnai/):

## Convert the `orfeome.xlsx` source file

```{r orfeome}
if (!file.exists("data-raw/orfeome.xlsx")) {
  download.file("http://dharmacon.gelifesciences.com/uploadedFiles/Resources/cernai-feeding-library.xlsx",
                "data-raw/orfeome.xlsx")
}
df <- readxl::read_excel("data-raw/orfeome.xlsx", sheet = 2)
colnames(df) <- seqcloudr::camel(colnames(df))
df <- dplyr::rename(df,
                    orfeomeHistorical = rnaiWell,
                    orfHistorical = orfIdWs112)

# Remove empty ORFs
df$orfHistorical <- gsub("^no match.*", NA, df$orfHistorical)
df <- subset(df, !is.na(df$orfHistorical))

# Select the desired columns, rename, then subset the bad wells:
df <- df[, c("orfHistorical", "plate", "row", "col", "orfeomeHistorical")]

# Set plate IDs as rownames
df$orfeome <- do.call(paste, c(df[, c("plate", "row", "col")], sep = "-"))
df$orfeome[1]
df$orfeome <- gsub("^(.*)-([0-9]{1})$", "\\1-0\\2", df$orfeome) # pad zeros
df$orfeome[1]
df$orfeome <- gsub("^([0-9]{5})-([A-Z]{1})-([0-9]{2})$", "\\1@\\2\\3", df$orfeome)
df$orfeome[1]
df$orfeome <- paste0("orfeome", df$orfeome)
df$orfeome[1]

df$historical <- paste0("MV_SV:mv_", df$orfHistorical)

orfeomeRawData <- df
devtools::use_data(orfeomeRawData, overwrite = TRUE)
```

```{r annotations}
# WormBase RESTful API request for RNAi annotations
if (file.exists("data/orfeomeRest.rda")) {
  data(orfeomeRest) 
} else {
  orfeomeRest <- historical2wbrnai(orfeomeRawData$historical)
  devtools::use_data(orfeomeRest, overwrite = TRUE)
}

# Oligo to Gene ID
if (file.exists("data/oligo2geneId.rda")) {
  data(oligo2geneId)
} else {
  source("data-raw/oligo2geneId.R")
}

df <- cbind(orfeomeRawData, orfeomeRest)
df <- df[, unique(names(df))]
df <- merge(df, oligo2geneId, by = "oligo", all.x = TRUE)

orfeomeData <- df
devtools::use_data(orfeomeData, overwrite = TRUE)
```
