utils::globalVariables(
    c(".",
      "ahringer96",
      "ahringer96Historical",
      "ahringer384",
      "cherrypick",
      "cloneData",
      "geneData",
      "gene",
      "genePair",
      "length",
      "orfeome96",
      "name",
      "sequence",
      "targetPrimary",
      "targetSecondary",
      "type")
)
